CHANGELOG = [
    {
        "id": 25,
        "version": "1.25",
        "timestamp": "06 Aug 2026, 08:27 IST",
        "category": "Feature",
        "title": "4 new Global Macro pages — Central Bank Rates, Fiscal Scorecard, Inflation & Growth, FX & Currencies",
        "description": [
            "global_macro_data.py — shared data layer: IMF Datamapper (8 indicators × 16 countries), BIS WS_CBPOL_M policy rates (40+ CBs), FRED spot FX (15 currency pairs); each dataset cached as parquet, refreshable via sidebar button",
            "Central Bank Rates — policy rate snapshot table with hiking/cutting/hold status, rate history multi-line chart, rate cycle heatmap, real policy rate (nominal − CPI) overlay",
            "Fiscal Scorecard — debt/GDP time series + ranking, fiscal balance chart with EU −3% threshold, primary balance, debt sustainability scatter quadrant",
            "Inflation & Growth — stagflation quadrant (CPI vs GDP growth), CPI + GDP time series with rankings, Phillips curve scatter (unemployment vs inflation)",
            "FX & Currencies — latest rates snapshot, indexed performance chart (base year selectable), annual returns heatmap (green=strengthened, red=weakened), carry trade indicator (inflation vs FX strength)",
            "All 4 pages wired into app.py APP_MAP; data loads from parquet cache on cold start — click Refresh Data on first use to pull live data from BIS/IMF/FRED",
        ],
    },
    {
        "id": 24,
        "version": "1.24",
        "timestamp": "05 Aug 2026, 21:05 IST",
        "category": "Polish",
        "title": "Capital Markets — financing model blurb truly full-width",
        "description": [
            "Moved the Market-based / Bank-based / Government debt-heavy blurb OUT of _section9_dna (where it was constrained by an HTML div) and into the main capital_markets() body as a native st.markdown call",
            "Native st.markdown (no unsafe_allow_html wrapper) renders at the full Streamlit content width — the div-based approach was the root cause of the narrow rendering",
        ],
    },
    {
        "id": 23,
        "version": "1.23",
        "timestamp": "05 Aug 2026, 20:48 IST",
        "category": "Polish",
        "title": "Capital Markets — financing model blurb full width, data sources footer white text",
        "description": [
            "Market-based / Bank-based / Government debt-heavy classifier text now uses width:100%;max-width:100% so it spans the full page rather than a constrained div",
            "Data sources footer text colour changed from muted grey (#475569) to white (#ffffff) for clear readability on the dark card background",
        ],
    },
    {
        "id": 22,
        "version": "1.22",
        "timestamp": "05 Aug 2026, 15:07 IST",
        "category": "Feature",
        "title": "Bond Portfolio — short positions + DV01 hedging scenario",
        "description": [
            "Qty input now allows negative values — negative qty = short position (like a futures short)",
            "Summary cards updated: Gross Exposure (total abs MV), Net Position (long − short), signed Portfolio DV01; DV01 card turns green when near-zero (duration-neutral)",
            "Automatic hedge callout: green banner when |DV01| < 1bp per $1M gross (DV01 hedged); amber guidance banner when shorts present but DV01 is still biased",
            "Portfolio Analytics: Country Allocation donut and Maturity Profile bars now use abs(MV) so shorts don't cancel longs visually",
            "Yield Positioning scatter bubble size uses abs(MV) — short positions show as correctly sized but still overlap longs",
            "Holdings table: new Position column (Long/Short); short rows highlighted in light red; weight column renamed to Gross Weight",
            "Rate shock ΔMV% now references gross exposure — makes percentage meaningful when net position is near zero",
            "DV01 by Bond bar chart already used signed DV01 — negative bars naturally show hedging positions (no change needed)",
        ],
    },
    {
        "id": 21,
        "version": "1.21",
        "timestamp": "05 Aug 2026, 14:13 IST",
        "category": "Polish",
        "title": "Bond Portfolio — replace custom qty stepper with native st.number_input",
        "description": [
            "Removed all custom column layouts and HTML for the +/- stepper; replaced with a single st.number_input (min=1, step=1) which provides native Streamlit +/- buttons with correct alignment and theme support",
            "Market value shown via st.caption below the input — no custom styling",
        ],
    },
    {
        "id": 20,
        "version": "1.20",
        "timestamp": "05 Aug 2026, 13:58 IST",
        "category": "Polish",
        "title": "Bond Portfolio — qty stepper on same row as bond name, fixed invisible number",
        "description": [
            "Stepper now shares a single row with the checkbox: [bond name] [−] [qty] [+] [$xM] — no separate row for buttons",
            "Fixed qty number invisible in light mode (was #f1f5f9 near-white); now uses color:inherit so it adapts to light/dark theme automatically",
            "Buttons are natural (not use_container_width) so they stay tight against the qty number",
        ],
    },
    {
        "id": 19,
        "version": "1.19",
        "timestamp": "05 Aug 2026, 12:54 IST",
        "category": "Polish",
        "title": "Bond Portfolio — compact quantity stepper",
        "description": [
            "Replaced the bulky full-width ± button columns with a narrow inline stepper: [−] qty [+] $xM on a single row",
            "Qty display is plain text (no box/border), buttons are default size (not use_container_width), market value sits inline to the right",
        ],
    },
    {
        "id": 18,
        "version": "1.18",
        "timestamp": "05 Aug 2026, 12:24 IST",
        "category": "Feature",
        "title": "Bond Portfolio — Yield Shock Scenario Builder + Risk & Impact Analysis",
        "description": [
            "New section at the bottom of Bond Portfolio: Yield Shock Scenario Builder — a compact grid of number inputs (basis points) organised by economy (rows) and maturity bucket (2Y / 3Y / 5Y / 10Y / 30Y columns); all 11 sovereign economies shown",
            "Portfolio economies shown in bold/white; non-portfolio economies greyed — shocks for economies not in portfolio produce zero P&L impact (noted in footer)",
            "9 preset buttons in two rows: parallel shifts (+25bp, +50bp, +100bp, -25bp, -50bp, -100bp), curve trades (Bear Steepen, Bull Flatten), and Reset; clicking a preset fills the entire grid and reruns instantly",
            "Impact analysis section auto-renders below the grid whenever at least one shock is non-zero — no separate submit button needed",
            "Impact analysis — 4 summary cards: Total ΔMV ($), Total ΔMV (% of portfolio), Biggest Gain (bond + amount), Biggest Loss (bond + amount)",
            "Impact analysis — P&L by country (horizontal bar, green/red by direction) and P&L by maturity bucket (vertical bar) shown side by side",
            "Impact analysis — full-width waterfall chart showing per-bond P&L attribution (sorted worst-to-best, Total bar at end)",
            "Impact analysis — detailed table: Bond, Country, Shock (bps), Old YTM, New YTM, Old Price, New Price, Qty, Old MV, New MV, ΔMV; rows coloured green/red",
            "Exact bond pricing used for impact (full bond_price() recalculation with new YTM), not duration approximation",
        ],
    },
    {
        "id": 17,
        "version": "1.17",
        "timestamp": "05 Aug 2026, 11:38 IST",
        "category": "Enhancement",
        "title": "Global Capital Markets — disk-cached data + Refresh button with stale-while-revalidate UX",
        "description": [
            "Data is now pre-fetched and committed to the repo as capital_markets_cache.parquet — app loads in under 1 second on cold start instead of spending 30–60 seconds calling World Bank + IMF APIs",
            "Refresh Data button added to the sidebar (below the year slider) — clicking it serves current data immediately, shows a banner 'Refreshing data…' while API calls run, then auto-swaps in the new data and dismisses the banner; no blank page during the refresh",
            "Last refreshed date shown in the sidebar so users know how fresh the data is",
            "Cache strategy: @st.cache_data with no TTL (data served from parquet file, not re-fetched unless Refresh is explicitly clicked); parquet file overwritten and Streamlit cache cleared on each refresh",
            "Fallback: if the parquet file is ever absent (fresh deploy without the file), the app fetches from APIs and saves the file for subsequent loads",
        ],
    },
    {
        "id": 16,
        "version": "1.16",
        "timestamp": "05 Aug 2026, 11:16 IST",
        "category": "Feature",
        "title": "Global Capital Markets Dashboard — equity vs bond markets across 10 countries",
        "description": [
            "New tab: Global Capital Markets — 9 sections, year slider 2005–2023, all charts update as you move through time",
            "Data sources: World Bank REST API (equity market cap, listed companies, population, stock turnover — free, no key) + IMF Datamapper API (GDP USD, Gross Govt Debt % GDP — free, no key); BIS corporate bond data excluded as their SDMX API returned 406/500 on all tested endpoints from this environment",
            "Section 1 — Global Snapshot: 6 metric cards (global equity cap, global govt bond market, total capital market, combined GDP, avg equity/GDP, avg bond/GDP)",
            "Section 2 — Market Size Comparison: stacked horizontal bar — equity + govt bonds side by side for all 10 countries (US dominance immediately visible, Japan/China bond market scale is striking)",
            "Section 3 — Equity vs Bond Scatter: signature chart — x=equity, y=govt bonds, bubble=GDP; 45° line shows which countries are bond-dominant (Japan) vs equity-dominant (USA, India)",
            "Section 4 — Equity/GDP: who has the deepest equity market relative to economy",
            "Section 5 — Govt Bond/GDP: Japan at 220% of GDP stands out immediately",
            "Section 6 — Total Capital Market Ranking: stacked Equity + Govt Bonds, ranked",
            "Section 7 — Historical Evolution: three time-series charts (equity, govt bonds, total) from 2005 to 2023 — watch China rise, India emerge, Japan stay flat, USA dominate throughout",
            "Section 8 — Interesting Ratios: Bond/Equity ratio bar chart + GDP vs Total Capital bubble chart (bubble ∝ population)",
            "Section 9 — Capital Markets DNA table: country, GDP, equity, govt bonds, equity/GDP, bond/GDP, bond/equity ratio, financing model classification (Market-based / Bank-based / Government debt-heavy / State-led / Mixed)",
            "Sidebar: year slider 2005–2023, section toggles so instructors can hide/show sections mid-lecture",
            "24-hour cache (ttl=86400) on data fetch — World Bank/IMF data doesn't change daily; cache cleared when app restarts",
        ],
    },
    {
        "id": 15,
        "version": "1.15",
        "timestamp": "05 Aug 2026, 08:28 IST",
        "category": "Feature",
        "title": "Correlation Matrix — filter by Asset Class from Instrument Metadata",
        "description": [
            "New sidebar multiselect: Asset Class — populated from the Instrument Metadata table in Firestore; shows all tagged asset classes present in the data (Fixed Income Bonds, FX, Equity Index, Commodity, Money Market, Credit Spread, Other) plus 'Untagged' for instruments not yet tagged",
            "Selecting one or more asset classes limits the correlation matrix to only the instruments belonging to those classes — e.g. select 'Fixed Income Bonds' only to see a pure fixed-income correlation heatmap",
            "All asset classes selected by default so existing behaviour is unchanged for users who don't filter",
            "Metadata loaded from Firestore with a 5-minute cache (ttl=300) to avoid hitting the DB on every rerun",
            "Guard added: if fewer than 2 instruments remain after filtering, a warning is shown instead of attempting to compute a degenerate matrix",
        ],
    },
    {
        "id": 14,
        "version": "1.14",
        "timestamp": "05 Aug 2026, 08:17 IST",
        "category": "Fix",
        "title": "Correlation heatmap — sparse columns (BTC etc.) no longer blank the matrix",
        "description": [
            "Root cause: .dropna() on the diff'd frame dropped any row where ANY column had a NaN — instruments like BTC (no data pre-2010) caused every row in early date ranges to be dropped, leaving an empty frame and the 'not enough data' warning even when plenty of data exists",
            "Fix: drop only the first row (always NaN from .diff()), then pass the full frame to .corr() which computes pairwise correlations using available observations per column pair — sparse columns no longer eliminate valid rows for other instruments",
        ],
    },
    {
        "id": 13,
        "version": "1.13",
        "timestamp": "05 Aug 2026, 07:37 IST",
        "category": "Feature",
        "title": "Persistent login — stay logged in until manual logout",
        "description": [
            "Auth cookie / JWT expiry extended from 30 days to 3650 days (10 years) — users remain logged in across browser restarts and sessions without needing to re-authenticate via Google OAuth",
            "Manual logout via the Logout button in the sidebar continues to work as before and immediately invalidates the session",
        ],
    },
    {
        "id": 12,
        "version": "1.12",
        "timestamp": "05 Aug 2026, 01:10 IST",
        "category": "Fix",
        "title": "Portfolio Rebalance freq error, heatmap silent failure, date picker CSS",
        "description": [
            "Portfolio Rebalance: updated pandas date_range frequency aliases — 'M'/'Q'/'6M'/'A' removed in pandas 2.2, replaced with 'ME'/'QE'/'6ME'/'YE' (month/quarter/year-end); tab was throwing ValueError on every load",
            "Correlation Heatmap: wrapped computation in try/except so errors surface as a visible red box instead of silently producing a blank screen; added numeric-column filter before .corr() to avoid dtype issues; added empty-range guard",
            "Correlation Heatmap: removed key= parameter from st.plotly_chart (only supported in Streamlit >=1.37, caused silent failure on deployed version); figure now persisted in session_state so it survives reruns after button state resets",
            "Date picker year selector: removed overly broad ul[role='listbox'] CSS that was setting max-height:none globally, causing the year list in st.date_input calendar popups to render without scroll (impossibly tall); the app selector dropdown with 9 items fits the default popup height without the override",
        ],
    },
    {
        "id": 11,
        "version": "1.11",
        "timestamp": "05 Aug 2026, 01:10 IST",
        "category": "UI",
        "title": "Bond Portfolio — compact selection UI, $100k face value, DV01 by maturity",
        "description": [
            "Bond selection redesigned: each bond row is now a compact checkbox (country name) with coupon/YTM shown in small text below — removes visual bulk from the accordion",
            "Face value changed to $100,000 per bond; qty = number of bonds (1 unit = 1 × $100k bond); stepper now increments by 1 instead of 10",
            "Stepper shows live market value as $xM below the − qty + control",
            "Maturity bucket headers simplified to a coloured underline only — removed heavy card styling that made the accordion disproportionately large",
            "New chart: DV01 by Maturity Bucket (2Y / 5Y / 10Y / 30Y) — shows where duration risk is concentrated across the curve; sits alongside the existing DV01 by Bond chart",
            "Yield Positioning scatter moved to full-width row below the 2×2 chart grid",
            "Holdings table: Qty column added; Market Value and DV01/bond shown in whole dollars",
        ],
    },
    {
        "id": 10,
        "version": "1.10",
        "timestamp": "05 Aug 2026, 10:00 IST",
        "category": "Feature",
        "title": "Bond Portfolio Builder + dropdown UX + Bond Pricing & Calculator rename",
        "description": [
            "New tab: Bond Portfolio Builder — select from a universe of 30 sovereign bonds across 11 countries (USA, Germany, UK, Japan, France, Italy, Canada, Australia, India, Brazil, China), covering 2Y–30Y maturities",
            "Each bond has its own accordion: set number of units, view price, Macaulay duration, modified duration, convexity, DV01/unit, total DV01, and a mini price–yield chart",
            "Portfolio-level Key Metrics: total market value, weighted-average YTM, Macaulay/modified duration, convexity, aggregate DV01",
            "Rate shock scenario table: ±25/50/100/200bp estimated ΔMV (exact first-order + convexity approximation), colour-coded",
            "Analytics section: Country Allocation donut, Maturity Profile bar chart (0–2Y / 2–5Y / 5–10Y / 10–30Y buckets), DV01 Contribution horizontal bar, Yield Positioning bubble scatter (x=maturity, y=YTM, size∝ market value)",
            "Holdings Summary table with download-to-CSV button",
            "Sidebar country filter narrows the bond universe available for selection",
            "Bond Pricing & Calculator renamed from Bond Calculator — name is consistent across dropdown and tab header",
            "App-selector dropdown: removed max-height constraint on the listbox popup so all apps show in one view without an inner scrollbar",
        ],
    },
    {
        "id": 9,
        "version": "1.9",
        "timestamp": "05 Aug 2026, 01:00 IST",
        "category": "Feature",
        "title": "OECD live rates, activated macro dashboard sections, Bond Calculator",
        "description": [
            "macro_data.py: live OECD MEI_FIN fetch (IRLT = 10Y yield, IRSTCI = short-term rate) for Japan, Italy, Brazil, India, China — refreshed every hour",
            "Annual 10Y yield for USA/UK/Canada/Germany/France sourced from Final.xlsx daily data (US10Y, UK10Y, CAD10Y, FGBLY, FOATY) — annual average computed; OECD fills remaining countries",
            "Instrument metadata (Firestore) auto-extends the 10Y mapping: any instrument tagged Fixed Income Bonds + 10Y maturity is automatically included in the annual yield calculation",
            "Global Macro Dashboard section 8 (10Y Govt Yield) and section 9 (Policy Rate) now live with real data and bar snapshots",
            "Correlation sections 11 & 12 now active: Debt/GDP vs 10Y Yield and Fiscal Balance vs 10Y Yield; each shows all-years scatter + latest-year scatter side by side",
            "load_macro_data now has ttl=3600 so metadata tag changes propagate within an hour",
            "New tab: Bond Calculator — full bond pricer with pure Python math (no QuantLib dependency)",
            "Bond Calculator features: price↔YTM (Newton-Raphson solve), Macaulay duration, modified duration, convexity, DV01, price-yield curve with duration tangent, ±25/50/100/200bp scenario table and bar chart, cashflow timeline, expandable concept explainer for students",
            "Bond Calculator is available to all logged-in users",
        ],
    },
    {
        "id": 8,
        "version": "1.8",
        "timestamp": "04 Aug 2026, 02:30 IST",
        "category": "Feature",
        "title": "Instrument Metadata editor + Global Yield Curves tab",
        "description": [
            "Bond Analytics → Instrument Metadata (admin only — professionalbuzz@gmail.com): inline-editable table covering every instrument in Final.xlsx; columns: Country, Asset Class (Fixed Income Bonds / FX / Equity Index / Commodity / Money Market / Credit Spread / Other), Maturity (1M–30Y / N/A), Notes",
            "Table uses st.data_editor with SelectboxColumn dropdowns; filter bar narrows the list by instrument name; Save button persists to Firestore app_config/instrument_metadata",
            "When a filtered view is saved, edits merge with the full dataset so hidden rows are never overwritten",
            "New app tab: Global Yield Curves — visible to all logged-in users",
            "Yield Curves sidebar: country multiselect, up to 10 date pickers (Add / × remove); each picker snaps to the nearest available date in the data",
            "One chart per selected country: x-axis = maturity tenors (1M → 30Y), y-axis = yield %, each selected date as a separate coloured line overlaid on one chart",
            "Hover shows tenor label, exact yield, and the date trace name; if selected date has no data the nearest date is shown with an arrow annotation in the legend",
            "firebase_utils.py: added get_instrument_metadata() and save_instrument_metadata() backed by Firestore app_config/instrument_metadata",
            "stream.py: Instrument Metadata section injected into Bond Analytics section selector for admin users only; non-admins see no change",
        ],
    },
    {
        "id": 7,
        "version": "1.7",
        "timestamp": "04 Aug 2026, 23:55 IST",
        "category": "Feature",
        "title": "Global Macro Dashboard — 13-section Bloomberg-style dashboard",
        "description": [
            "New 'Global Macro Dashboard' tab added to the app selector — available to all logged-in users",
            "10 countries: USA, China, Japan, Germany, France, Italy, United Kingdom, India, Canada, Brazil — 2008–2025",
            "Data sourced from IMF WEO (GDP, real growth, inflation, fiscal balance, primary balance) and IMF Global Debt Database (GDD: govt debt/GDP); stored in Master_Fixed_Income_Data.xlsx",
            "Note: mainland China missing from WEO extract — GDP/growth/inflation/fiscal balance show as N/A for China; Debt/GDP from GDD is available for all 10 countries",
            "Section 1: Global Snapshot — average metric cards (GDP, growth, inflation, debt/GDP, fiscal balance) + per-country scorecard table for the latest selected year",
            "Section 2: GDP (USD bn) — time-series line chart + latest-year bar chart",
            "Section 3: Real GDP Growth % — time-series",
            "Section 4: Government Debt Outstanding (USD bn) — calculated as Debt/GDP × GDP USD",
            "Section 5: Government Debt/GDP % — GDD-sourced, time-series + bar",
            "Section 6: Fiscal Balance — side-by-side Net Lending/Borrowing % GDP and Primary Balance % GDP",
            "Section 7: CPI Inflation % — time-series + bar",
            "Sections 8–12: 10Y Yield, Policy Rate, Bond Issuance, Issuance/GDP, two correlation scatters — 'Data Pending' placeholders; will auto-populate when data is added",
            "Section 13: Download filtered dataset as CSV",
            "Sidebar filters: country multiselect, year range slider, compare mode toggle (one chart per metric vs small multiples 2-column grid)",
            "Bloomberg-style dark Plotly charts (plotly_dark template, #0f172a plot bg, #1e293b card bg) with per-country color palette consistent across all sections",
            "macro_data.py: @st.cache_data data loader merging WEO_Raw and GDD_Raw sheets; falls back to WEO gross debt % GDP when GDD is unavailable",
        ],
    },
    {
        "id": 6,
        "version": "1.6",
        "timestamp": "04 Aug 2026, 21:52 IST",
        "category": "Fix",
        "title": "Sidebar expand definitively fixed — stop hiding header entirely",
        "description": [
            "stToolbar selector was still catching the sidebar expand control in Streamlit's DOM, keeping the sidebar permanently collapsed",
            "Removed all header/toolbar CSS hiding — only #MainMenu and footer are hidden (pure branding, no interactive controls)",
            "Sidebar toggle now always accessible regardless of Streamlit version's internal DOM layout",
        ],
    },
    {
        "id": 5,
        "version": "1.5",
        "timestamp": "04 Aug 2026, 21:45 IST",
        "category": "Fix",
        "title": "Restore sidebar expand button after collapse",
        "description": [
            "header { visibility: hidden } was hiding the Streamlit sidebar expand chevron along with the toolbar, making the sidebar unrecoverable once collapsed",
            "Replaced with [data-testid='stToolbar'] { visibility: hidden } — hides the Deploy/options toolbar only, leaves the sidebar toggle visible",
        ],
    },
    {
        "id": 4,
        "version": "1.4",
        "timestamp": "04 Aug 2026, 21:38 IST",
        "category": "UI",
        "title": "Logout button moved to sidebar bottom with divider",
        "description": [
            "Logout button moved from top of sidebar to bottom — renders after all tab-specific controls so it stays out of the way during normal use",
            "Solid #475569 horizontal rule added above the button as a visual separator",
            "Button remains full-width (inherits existing width:100% sidebar button CSS)",
        ],
    },
    {
        "id": 3,
        "version": "1.3",
        "timestamp": "04 Aug 2026, 21:26 IST",
        "category": "Performance",
        "title": "Slim Docker image · dark sidebar theme · EmailCrm removed",
        "description": [
            "Switched Docker base from mcr.microsoft.com/playwright/python:v1.21.0-focal (~1.5 GB) to python:3.11-slim (~120 MB) — eliminates bundled browser binaries that the live app never uses; expected 60-70% reduction in cold-start time",
            "Added Docker layer caching: requirements.txt is copied and pip-installed before the app code, so re-deploys only reinstall packages when requirements.txt changes (was reinstalling everything on every push)",
            "Playwright Python packages kept in requirements.txt for future use (scrap.py); browser binaries not installed — add 'RUN playwright install --with-deps chromium' to Dockerfile when ready to activate",
            "Removed streamlit-aggrid from requirements.txt — was only used by EmailCrm which is now removed",
            "EmailCrm module removed entirely (email_crm_gmail.py, email_crm_outreach_chintanthakkar.py, __init__.py deleted)",
            "Added .streamlit/config.toml: navy primary (#1e40af), off-white background (#f8f9fc), white widget backgrounds, system sans-serif font — applied app-wide via Streamlit theming",
            "Dark sidebar (#1e293b) with matching select boxes, date inputs, buttons, and slider in slate palette — hides Streamlit header/footer/hamburger menu for a cleaner product feel",
            "Bond Analytics moved to first position in app dropdown (was second after News Summarizer)",
        ],
    },
    {
        "id": 2,
        "version": "1.2",
        "timestamp": "03 Aug 2026, 11:08 IST",
        "category": "Performance",
        "title": "Data pre-load on login — sidebar controls no longer freeze on cold start",
        "description": [
            "market data (Final.xlsx) is now loaded once in app.py immediately after login, before any tab function runs",
            "a 'Loading market data...' spinner shows in the main area during this one-time load — sidebar app/section selectors remain fully interactive",
            "all tab functions call load_data() which returns the @st.cache_data result instantly; no tab ever blocks waiting for disk I/O again",
            "pre-load runs once per browser session (tracked via st.session_state['data_warmed']); subsequent tab switches and reruns are unaffected",
        ],
    },
    {
        "id": 1,
        "version": "1.1",
        "timestamp": "03 Aug 2026, 10:46 IST",
        "category": "Refactor",
        "title": "Initial refactor — shared utilities, dead code removal, changelog added",
        "description": [
            "Extracted shared Firebase formula CRUD (get/add/delete) into firebase_utils.py — was copy-pasted across GridTab, CustomTab, and HeatmapTab; any future fix now in one place",
            "Extracted shared load_data() into data.py — was defined separately in all 4 tabs reading the same Final.xlsx; now a single @st.cache_data call app-wide",
            "Fixed instrument column inconsistency — HeatmapTab sliced df.columns[1:32] (31 cols), CustomTab sliced df.columns[1:34] (33 cols); unified to df.columns[1:] so all instruments are included dynamically",
            "Replaced unsafe eval() in CustomTab with df.eval() — matches GridTab's existing approach; removes Python builtins escape vector in custom formula evaluation",
            "Fixed deprecated st.experimental_rerun() → st.rerun() in portfolio_rebalance.py — would raise AttributeError on Streamlit ≥1.28",
            "Removed debug print('Saved Formulas', ...) in GridTab.py — was logging each user's saved formulas to stdout on every render",
            "Removed unused imports in CustomTab.py — authenticator, firebase_admin, credentials, get_app, initialize_app were imported but never referenced",
            "Removed dead commented-out code from stream.py (old home_page implementation) and portfolio_rebalance.py (commented file upload block)",
            "Added admin-only Changelog tab visible to professionalbuzz@gmail.com (requires ADMINS env var on Render to include this email)",
        ],
    },
]
